### ISSUE TITLE
Fails while replacing Nginx config

### ISSUE THREAD

**Issue by ciaranmcnulty** [guoxiao/homebrew-php7#1]
==> /usr/local/Cellar/php7/7.0.0alpha1/bin/pear config-set php_ini /usr/local/et
Error: inreplace failed
/usr/local/etc/php/7/php-fpm.conf:
  expected replacement of /^;include\s_=.+$/ with ";include=/usr/local/etc/php/7/fpm.d/_.conf"
  expected replacement of /^;?listen.mode\s_=.+$/ with "listen.mode = 0666"
  expected replacement of /^;?pm.max_children\s_=.+$/ with "pm.max_children = 10"
  expected replacement of /^;?pm.start_servers\s_=.+$/ with "pm.start_servers = 3"
  expected replacement of /^;?pm.min_spare_servers\s_=.+$/ with "pm.min_spare_servers = 2"
  expected replacement of /^;?pm.max_spare_servers\s*=.+$/ with "pm.max_spare_servers = 5"

**Comment by pylebecq** [comment]
This is due to https://github.com/php/php-src/commit/9f189dd29075589aeb3c88c4e2860d6ae0730f27

**Comment by steinmb** [comment]
Confirm that this fix the build.
